import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "./components/Navbar/ResponsiveNav";
import Footer from "./components/Footer/Footer";
import ScrollToTop from "./components/Helper/ScrollToTop";

const oswald = Oswald({
  weight:['200', '300', '400', '500', '600', '700'],
  subsets:['latin']
})

export const metadata: Metadata = {
  title: "Sports Website template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={oswald.className}>
          <ResponsiveNav />
        {children}
          <Footer />
          <ScrollToTop />
      </body>
    </html>
  );
}
